/* font_render.c — Text renderer for glossad
 *
 * Loads pre-densified font data from font_data.json (generated by Python
 * from EMSAllure.svg). Renders text as stroke JSON for uinject.
 *
 * Key facts (from CRUSH.md):
 * - Origin is TOP-CENTER on reMarkable
 * - SVG uses Y-up, rm uses Y-down: sy = -gy * scale
 * - Point format: [x, y, speed, width, direction, pressure]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>

/* ─── constants (match Python) ───────────────────────────────────── */

#define DEFAULT_SCALE     0.06f
#define DEFAULT_X        -550.0f
#define DEFAULT_Y         200.0f
#define LINE_HEIGHT       1.4f
#define MAX_LINE_WIDTH    1100.0f
#define GLYPH_HEIGHT      800.0f
#define PAGE_BOTTOM       1820.0f
#define MAX_GLYPHS        128
#define MAX_POLYLINES     16
#define MAX_POINTS_PER_PL 512

/* ─── data structures ────────────────────────────────────────────── */

typedef struct {
    float x, y;
} Point2D;

typedef struct {
    Point2D pts[MAX_POINTS_PER_PL];
    int count;
} Polyline;

typedef struct {
    Polyline polylines[MAX_POLYLINES];
    int num_polylines;
    float advance;
} Glyph;

typedef struct {
    Glyph glyphs[MAX_GLYPHS];
    int loaded;
} FontData;

/* Simple LCG RNG for deterministic jitter */
typedef struct {
    unsigned long state;
} RNG;

static void rng_seed(RNG *rng, const char *seed_str) {
    unsigned long h = 5381;
    while (*seed_str)
        h = ((h << 5) + h) + (unsigned char)*seed_str++;
    rng->state = h;
}

static float rng_uniform(RNG *rng, float lo, float hi) {
    rng->state = rng->state * 1103515245 + 12345;
    float t = (float)((rng->state >> 16) & 0x7FFF) / 32767.0f;
    return lo + t * (hi - lo);
}

static int rng_randint(RNG *rng, int lo, int hi) {
    rng->state = rng->state * 1103515245 + 12345;
    int range = hi - lo + 1;
    return lo + (int)(((rng->state >> 16) & 0x7FFF) % range);
}

/* ─── JSON font loader ───────────────────────────────────────────── */

/* Minimal JSON parser for font_data.json format:
 * {"H": {"adv": 939.0, "polys": [[[x,y],...], ...]}, ...}
 */
static const char *skip_ws(const char *p) {
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    return p;
}

static int load_font_json(FontData *font, const char *path) {
    FILE *fp = fopen(path, "r");
    if (!fp) return -1;
    fseek(fp, 0, SEEK_END);
    long sz = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    char *data = malloc(sz + 1);
    if (!data) { fclose(fp); return -1; }
    fread(data, 1, sz, fp);
    data[sz] = '\0';
    fclose(fp);

    /* Initialize all glyphs */
    for (int i = 0; i < MAX_GLYPHS; i++) {
        font->glyphs[i].num_polylines = 0;
        font->glyphs[i].advance = 378.0f; /* default */
    }

    const char *p = skip_ws(data);
    if (*p != '{') { free(data); return -1; }
    p++;

    /* Parse each character entry */
    while (*p) {
        p = skip_ws(p);
        if (*p == '}') break;
        if (*p == ',') { p++; continue; }

        /* Key: single character or escape sequence */
        if (*p != '"') { p++; continue; }
        p++; /* skip opening quote */
        unsigned char ch = 0;
        if (*p == '\\') {
            p++;
            if (*p == 'n') ch = '\n';
            else if (*p == 't') ch = '\t';
            else if (*p == '"') ch = '"';
            else if (*p == '\\') ch = '\\';
            else ch = *p;
            p++;
        } else {
            ch = (unsigned char)*p++;
        }
        if (*p == '"') p++; /* skip closing quote */
        p = skip_ws(p);
        if (*p == ':') p++;
        p = skip_ws(p);

        if (ch < MAX_GLYPHS && *p == '{') {
            p++; /* skip { */
            Glyph *g = &font->glyphs[ch];

            /* Parse "adv" and "polys" fields */
            while (*p && *p != '}') {
                p = skip_ws(p);
                if (*p == ',') { p++; continue; }
                if (*p == '"') {
                    /* Field name */
                    p++;
                    char field[16] = {0};
                    int fi = 0;
                    while (*p && *p != '"' && fi < 15) field[fi++] = *p++;
                    if (*p == '"') p++;
                    p = skip_ws(p);
                    if (*p == ':') p++;
                    p = skip_ws(p);

                    if (strcmp(field, "adv") == 0) {
                        char *end;
                        g->advance = strtod(p, &end);
                        p = end;
                    } else if (strcmp(field, "polys") == 0) {
                        /* Parse array of polylines: [[[x,y],...], ...] */
                        if (*p == '[') {
                            p++; /* skip outer [ */
                            int pl_idx = 0;
                            while (*p && *p != ']' && pl_idx < MAX_POLYLINES) {
                                p = skip_ws(p);
                                if (*p == ',') { p++; continue; }
                                if (*p == '[') {
                                    p++; /* skip polyline [ */
                                    g->polylines[pl_idx].count = 0;
                                    while (*p && *p != ']') {
                                        p = skip_ws(p);
                                        if (*p == ',') { p++; continue; }
                                        if (*p == '[') {
                                            p++; /* skip point [ */
                                            char *e1, *e2;
                                            float px = strtod(p, &e1);
                                            p = skip_ws(e1);
                                            if (*p == ',') p++;
                                            float py = strtod(p, &e2);
                                            p = e2;
                                            p = skip_ws(p);
                                            if (*p == ']') p++;

                                            int cnt = g->polylines[pl_idx].count;
                                            if (cnt < MAX_POINTS_PER_PL) {
                                                g->polylines[pl_idx].pts[cnt].x = px;
                                                g->polylines[pl_idx].pts[cnt].y = py;
                                                g->polylines[pl_idx].count = cnt + 1;
                                            }
                                        } else {
                                            p++;
                                        }
                                    }
                                    if (*p == ']') p++; /* skip polyline ] */
                                    if (g->polylines[pl_idx].count >= 2)
                                        pl_idx++;
                                } else {
                                    p++;
                                }
                            }
                            g->num_polylines = pl_idx;
                            if (*p == ']') p++; /* skip outer ] */
                        }
                    }
                } else {
                    p++;
                }
            }
            if (*p == '}') p++;
        } else {
            /* Skip unknown value */
            int depth = 0;
            while (*p) {
                if (*p == '{' || *p == '[') depth++;
                else if (*p == '}' || *p == ']') { if (depth == 0) break; depth--; }
                else if (*p == ',' && depth == 0) break;
                p++;
            }
        }
    }

    free(data);
    font->loaded = 1;
    return 0;
}

/* ─── text → strokes JSON ────────────────────────────────────────── */

/* Render text to stroke JSON file. Returns number of strokes written,
 * or -1 on error. Sets *consumed to the number of bytes of text that
 * fit on the page (for multi-page support). */
int render_text_to_json(const char *text, const char *output_path,
                        float origin_x, float origin_y,
                        const char *font_path, int *consumed) {
    static FontData font;
    if (!font.loaded) {
        if (load_font_json(&font, font_path) != 0) {
            fprintf(stderr, "[font] Failed to load %s\n", font_path);
            return -1;
        }
    }

    /* Seed RNG deterministically */
    char seed[512];
    snprintf(seed, sizeof(seed), "%s%.0f", text, origin_x);
    RNG rng;
    rng_seed(&rng, seed);

    float cursor_x = origin_x;
    float cursor_y = origin_y;
    float space_adv = font.glyphs[' '].advance * DEFAULT_SCALE;

    FILE *out = fopen(output_path, "w");
    if (!out) return -1;

    fprintf(out, "[");
    int total_strokes = 0;
    int first_stroke = 1;

    const char *word_start = text;
    while (*word_start) {
        while (*word_start == ' ') word_start++;
        if (!*word_start) break;

        const char *word_end = word_start;
        while (*word_end && *word_end != ' ') word_end++;

        /* Word wrap check */
        float word_width = 0;
        for (const char *c = word_start; c < word_end; c++) {
            unsigned char ch = (unsigned char)*c;
            if (ch < MAX_GLYPHS)
                word_width += font.glyphs[ch].advance * DEFAULT_SCALE;
        }
        if (cursor_x + word_width > origin_x + MAX_LINE_WIDTH && cursor_x > origin_x) {
            cursor_x = origin_x;
            cursor_y += GLYPH_HEIGHT * DEFAULT_SCALE * LINE_HEIGHT;
        }

        /* Stop if we'd render below the page bottom */
        if (cursor_y > PAGE_BOTTOM) {
            if (consumed) *consumed = (int)(word_start - text);
            break;
        }

        for (const char *c = word_start; c < word_end; c++) {
            unsigned char ch = (unsigned char)*c;
            if (ch >= MAX_GLYPHS) continue;
            Glyph *g = &font.glyphs[ch];
            float adv = g->advance * DEFAULT_SCALE;

            if (g->num_polylines == 0) {
                cursor_x += adv;
                continue;
            }

            float x_jitter = rng_uniform(&rng, -2.0f, 2.0f);
            float y_jitter = rng_uniform(&rng, -1.5f, 0.5f);
            float slant = rng_uniform(&rng, -0.015f, 0.015f);

            /* Global point counter across all polylines in this glyph
             * so wobble phase is continuous and strokes connect properly */
            int global_pt = 0;

            for (int pl = 0; pl < g->num_polylines; pl++) {
                Polyline *src = &g->polylines[pl];
                if (src->count < 2) continue;

                /* Emit stroke JSON (points are already densified) */
                if (!first_stroke) fprintf(out, ",");
                first_stroke = 0;

                float min_x = 1e9f, min_y = 1e9f, max_x = -1e9f, max_y = -1e9f;
                fprintf(out, "{\"points\":[");

                for (int j = 0; j < src->count; j++) {
                    float gx = src->pts[j].x;
                    float gy = src->pts[j].y;

                    float sx = gx * DEFAULT_SCALE;
                    float sy = -gy * DEFAULT_SCALE;  /* Y flip */
                    sx += sy * slant;
                    float wobble = sinf(cursor_x * 0.01f + global_pt * 0.3f) * 0.8f;
                    float px = cursor_x + sx + x_jitter;
                    float py = cursor_y + sy + y_jitter + wobble;

                    int speed = 4 + rng_randint(&rng, 0, 8);
                    int direction = 80 + rng_randint(&rng, 0, 30);
                    int width = 10 + rng_randint(&rng, 0, 3);
                    int pressure = 160 + rng_randint(&rng, 0, 30);

                    if (j > 0) fprintf(out, ",");
                    fprintf(out, "[%.1f,%.1f,%d,%d,%d,%d]",
                            px, py, speed, width, direction, pressure);

                    if (px < min_x) min_x = px;
                    if (py < min_y) min_y = py;
                    if (px > max_x) max_x = px;
                    if (py > max_y) max_y = py;
                    global_pt++;
                }

                fprintf(out, "],\"rgba\":4278190080,\"color\":0,"
                            "\"bounds\":[%.1f,%.1f,%.1f,%.1f],"
                            "\"tool\":15,\"maskScale\":2.0,\"thickness\":2.0}",
                        min_x, min_y, max_x - min_x, max_y - min_y);

                total_strokes++;
            }

            cursor_x += adv + fmaxf(-2.0f, x_jitter * 0.1f) + fabsf(rng_uniform(&rng, -1.0f, 1.0f));
        }

        cursor_x += space_adv + rng_uniform(&rng, -2.0f, 2.0f);
        word_start = word_end;
    }

    fprintf(out, "]");
    fclose(out);
    if (consumed) *consumed = (int)(word_start - text);
    return total_strokes;
}
